Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Setup for the Master Node (Server)
  config.vm.define "server" do |server|
    server.vm.hostname = "flafiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    # Provider customization
    server.vm.provider "virtualbox" do |vb|
      vb.name = "flafiS"
      vb.memory = "2048"
      vb.cpus = "2"
    end
    server.vm.provision "shell", path: "scripts/gen_ssh_key.sh"
  end

  # Setup for the Worker Node (Agent)
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "flafiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "flafiSW"
      vb.memory = "1536"
      vb.cpus = "1"
    end

    worker.vm.provision "shell", path: "scripts/gen_ssh_key.sh"

    worker.trigger.after :up do |trigger|
      trigger.name = "Exchange SSH keys"
      trigger.run = {
        path: "scripts/exchange_keys.sh"
      }
    end
  end

  # === GLOBAL ANSIBLE PROVISIONER ===
  # Placing it here lets it orchestrate both nodes together
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "confs/playbook.yaml"
    ansible.limit = "all" # Prevents Vagrant from filtering out the server node
    ansible.groups = {
      "k3s_master" => ["server"],
      "k3s_worker" => ["worker"]
    }
    ansible.compatibility_mode = "2.0"
  end
end