Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Setup for the Master Node (Server)
  config.vm.define "server" do |server|
    server.vm.hostname = "flafiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    # Provider customization
    server.vm.provider "virtualbox" do |vb|
      vb.name = "flafiS"  # Set the VM name in VirtualBox
      vb.memory = "2048"  # Allocate 2GB RAM
      vb.cpus = "2"       # Allocate 2 vCPUs
    end
    server.vm.provision "shell", path: "scripts/gen_ssh_key.sh"
  end

  # Setup for the Worker Node (Agent)
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "flafiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "flafiSW"  # Set the VM name in VirtualBox
      vb.memory = "1536"  # Allocate 1.5GB RAM
      vb.cpus = "1"       # Allocate 1 vCPU
    end
    worker.vm.provision "shell", path: "scripts/gen_ssh_key.sh"
  end

  # Runs after 'vagrant up'
  config.trigger.after :up do |trigger|
    trigger.name = "Exchange SSH keys"
    trigger.run = {
      path: "scripts/exchange_keys.sh"
    }
end

#ansible